AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 3

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref S3Bucket
        - S3WritePolicy:
            BucketName: !Ref S3Bucket
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3Bucket
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            Path: /
            Method: get

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketNameParameter

Parameters:
  BucketNameParameter:
    Type: String
    Description: Name of the S3 bucket to store data.json